### PR TITLE
Add Cuda 555.42.06

### PR DESCRIPTION
**Pull request by EriksRemess**
from runfile https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run

addresses the issue https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/265

### CODE REVIEW

**Comment by guihkx** [comment]
Hmm, won't this re-introduce issue #224?

Which was "solved" by creating a [GitHub release](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/releases/tag/cuda) with only the smaller `.run` file.

I think maintainers will have to do the same for this version, too:

```
curl -LO https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run
chmod +x cuda_12.5.1_555.42.06_linux.run
./cuda_12.5.1_555.42.06_linux.run --extract=$PWD
```

And then upload `NVIDIA-Linux-x86_64-555.42.06.run` to a GH Release.

**Comment by EriksRemess** [comment]
I don't expect this to be merged before extracting and uploading driver runfile to github releases. I don't have access to do that. See comment here https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/224#issuecomment-1893017543

Also nVidia could release proper runfiles any time.

**Comment by 404NetworkError** [comment]
@EriksRemess New binaries are located in the [releases](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/releases/cuda/).

**Comment by 404NetworkError** [comment]
I get different hashes. Can you please confirm your hashes are correct?

**Comment by EriksRemess** [comment]
Hashes fixed now, new locations added and update-data.sh script updated for cuda versions

**Comment by 404NetworkError** [comment]
Thank you very much for your support!

**Pull request merged**
