### PR TITLE
Add 545.23.08 (requires some hacky stuff, since this is a CUDA-only driver)

### PR DESCRIPTION
**Pull request by aloisklink**
Rarely[^1], the NVIDIA CUDA team creates a new CUDA release that comes with a package driver that is slightly ahead of the normally downloadable driver.

[^1]: See https://forums.developer.nvidia.com/t/linux-525-60-11-need-525-60-13/237876 and https://forums.developer.nvidia.com/t/545-23-08-is-not-listed-in-the-nvidia-driver-downloads-page/273181.

For example, the current **Latest Beta Version** available on https://www.nvidia.com/en-us/drivers/unix/ is [545.23.06](https://www.nvidia.com/Download/driverResults.aspx/212964/en-us).

However, the [CUDA Toolkit 12.3.1](https://developer.nvidia.com/cuda-downloads) (November 2023) release from https://developer.nvidia.com/cuda-toolkit-archive comes with the **545.23.08** driver. This 545.23.08 is **only** available to download with CUDA, and isn't available on any page where you can search for drivers.

But it does mean that anybody on Linux that has CUDA setup and does a `sudo apt upgrade` or `dnf upgrade` will get the 545.23.08 driver, which breaks their Flatpak apps.

It seems like NVIDIA is aware of this issue, but since it's a hotfix, they're not too worried about the versions of regular/CUDA drivers not matching: https://forums.developer.nvidia.com/t/545-23-08-is-not-listed-in-the-nvidia-driver-downloads-page/273181/7

Fixes https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/213, closes https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/212

---

This PR adds support for installing drivers from CUDA `.run` files from https://developer.nvidia.com/cuda-toolkit-archive, since it's the only place I could find the `NVIDIA-Linux-x86_64-545.23.08.run` driver.

These CUDA `.run` files are made with `makeself` v2.1.4, which don't have a `skip=` field, so we need to slightly modify how we find the offset for the beginning of the tar.

The CUDA driver's `.run` file is then located inside the CUDA `.run` file under `./builds/NVIDIA-Linux-x86_64-545.23.08.run` (or `./builds/NVIDIA-Linux-aarch64-545.23.08.run` for ARM), so essentially, we need to parse and extract the outer CUDA `.run` file, before parsing and extracting the inner CUDA driver `.run` file.

### Potential issues

- Downloading `cuda_12.3.1_545.23.08_linux.run` is about 10x larger than downloading just the driver.
  - We could download just the driver as a `.deb` or ` .rpm` from the Debian/RedHat NVIDIA CUDA repos, but I thought it would make the code more complicated, so I didn't think it was worth making the change, especially since the CUDA drivers only seem to diverge from the regular drivers every few months.
  - We could host the `NVIDIA-Linux-x86_64-545.23.08.run` somewhere and download from there instead. It sounds like Nvidia is happy for us to redistribute the binaries (see https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/156#issuecomment-1500426184).
- I've tested this works on x86_64, but I don't have an aarch64 or i386 system to test with those.

### CODE REVIEW

**Comment by kmittman** [comment]
Hi @aloisklink,
Instead of `sh cuda_*.run --tar mxvf` [extraction](https://github.com/NVIDIA/yum-packaging-precompiled-kmod/#download-a-nvidia-driver-runfile), another option is the [binary archive](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#tarball-and-zip-archive-deliverables) format (tarball + JSON manifest) deliverables @ `/compute/$product/redist/$component/$os-$arch/$component-$os-$arch-$version-archive.tar.xz`

- NVIDIA driver bundled with **CUDA 12.3.1** release [redistrib_12.3.1.json](https://developer.download.nvidia.com/compute/cuda/redist/redistrib_12.3.1.json) `545.23.08`
  - listing: https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-x86_64/
- NVIDIA driver Datacenter **535** release [redistrib_535.129.03.json](https://developer.download.nvidia.com/compute/nvidia-driver/redist/redistrib_535.129.03.json) `535.129.03`
  - listing: https://developer.download.nvidia.com/compute/nvidia-driver/redist/nvidia_driver/linux-x86_64/
  
 More info and issue tracker here: https://github.com/NVIDIA/build-system-archive-import-examples

**Comment by aloisklink** [comment]
> Instead of `sh cuda_*.run --tar mxvf` [extraction](https://github.com/NVIDIA/yum-packaging-precompiled-kmod/#download-a-nvidia-driver-runfile), another option is the [binary archive](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#tarball-and-zip-archive-deliverables) format (tarball + JSON manifest) deliverables @ `/compute/$product/redist/$component/$os-$arch/$component-$os-$arch-$version-archive.tar.xz`
> 
> * NVIDIA driver bundled with **CUDA 12.3.1** release [redistrib_12.3.1.json](https://developer.download.nvidia.com/compute/cuda/redist/redistrib_12.3.1.json) `545.23.08`
> 
>   * listing: https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-x86_64/

Wow! That [`nvidia_driver-linux-x86_64-545.23.08-archive.tar.xz`](https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/linux-x86_64/) file looks almost perfect! Unfortunately it's in a different format from the `.tar` in the runfiles, e.g. shared-libraries are stored under `lib/` instead of at the root of the `.tar`.

The [`nvidia-apply-extra.c`](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commits/master/nvidia-apply-extra.c) command currently only supports the tarfile structure from a runfile. It should be possible in theory to extract the non-runfile `.tar.gz`, but in my opinion, it's not worth the effort, since 98% of the time, the CUDA drivers are the same as regular NVIDIA drivers, so we can just use those runfiles.

Plus, it sounds like we can somehow store only the exact NVIDIA binaries we need in a flatpak package (see PR https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/167), which would probably be a better way of fixing this issue, but I'm very inexperienced with Flatpak/Flathub, so I can't really comment on that :)

It's good to see that [you've also written that way to get an NVIDIA CUDA driver runfile is to extract it from a CUDA runfile](https://github.com/NVIDIA/yum-packaging-precompiled-kmod/blob/95b64505aa55381756c6c1514a9099f37a1812fa/README.md#download-a-nvidia-driver-runfile), so my approach isn't totally crazy :).

Potentially, one of the admins of this repo could also just manually extract the CUDA driver runfile and upload it as a [GitHub Release Asset](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases), in order to avoid downloading the entire CUDA runfile. I don't believe that violates NVIDIA's or GitHub's terms of service, but I'll leave that up to someone more experienced with Flatpak to decide!

**Comment by IanTrudel** [comment]
Will this PR be approved and available on flathub? I attempted to build it but to no avail. Going back to a previous version of CUDA is not an option for me.

**Comment by rainydaysavings** [comment]
I concur, hope it'll be approved soon

**Comment by idrilirdi** [comment]
Same here, this is direly needed

**Comment by IanTrudel** [comment]
The patch made it to flathub but it's not working on my end. `Warning: Error pulling from repo: Error reading from file: Bad address`

**Pull request merged**
