### PR TITLE
Add CI and optimize build time

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by TingPing** [comment]
Not sure why CI isn't running here, but it does on my fork: https://github.com/TingPing/org.freedesktop.Platform.GL.nvidia/actions

**Comment by guihkx** [comment]
>Not sure why CI isn't running here

The PR needs to get merged first.

One question on the CI part: Every time this workflow runs, it has to download 92 GiB (and growing) of driver files from NVIDIA servers.

Do you think such traffic generation could eventually jeopardize Flathub's account on GitHub?

**Comment by guihkx** [comment]
Actually, never mind the comment above. No driver files are ever downloaded...

**Comment by TingPing** [comment]
> One question on the CI part: Every time this workflow runs, it has to download 92 GiB (and growing) of driver files from NVIDIA servers.

The build step doesn't download anything. Only `update-data.sh`.

**Comment by TingPing** [comment]
It is kinda pointless to build every version anyway, as they are all basically the same.

We can evaluate that later I guess.

**Comment by guihkx** [comment]
>It is kinda pointless to build every version anyway, as they are all basically the same.

Good point. Though it should be fairly easy to modify the current workflow to only build once, for the most recent beta version, e.g. (untested):

```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index cb75dd6..3cc6ab2 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,4 +17,6 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Build
-        run: make
\ No newline at end of file
+        run: |
+          echo 'DRIVER_VERSIONS="${BETA_VERSIONS[0]}"' >> versions.sh
+          make
```

And then perhaps [QEMU](https://github.com/docker/setup-qemu-action) could be added to also build once for `aarch64`.

**Comment by guihkx** [comment]
Still not building a single driver... Stupid Bash. :sweat_smile:

```bash
echo 'DRIVER_VERSIONS="${BETA_VERSIONS%% *}"' >> versions.sh
```

That should do it...

**Pull request merged**
