### PR TITLE
Add Vulkan 418.42.02

### PR DESCRIPTION
**Pull request by 404NetworkError**

### CODE REVIEW

**Comment by TingPing** [comment]
@404NetworkError 	Curious btw did you verify these (the vulkan versions) actually load and work?

**Comment by 404NetworkError** [comment]
I never thought about doing that. I guess I was hoping someone else would've complained by now if it didn't.

I can do it later today, though, and report back.

**Comment by 404NetworkError** [comment]
@TingPing I have confirmed that the Vulkan builds work.

Tested on:
* Ubuntu 18.04.2 64-bit
  * NVIDIA 418.42.02
  * NVIDIA 419.31.03
  * flatpak 1.0.7
* Fedora 29 64-bit (GNOME and KDE)
  * NVIDIA 418.42.02
  * flatpak 1.2.3

**Comment by TingPing** [comment]
Great, thanks.

**Pull request merged**
