### PR TITLE
Switch from extra-data to normal package

### PR DESCRIPTION
**Pull request by TingPing**
Nvidia has clarified that they allow redistribution for our use-case.

### CODE REVIEW

**Comment by TingPing** [comment]
I've only done some basic tests, but further testing would be appreciated.

**Comment by foundObjects** [comment]
I tried some simple tests here, a bunch of flatpak things like flatpak steam complain that the GL32 version isn't installed. The games I tried didn't launch on the nvidia gpu in my laptop.

The Green with Envy flatpak refuses to run stating that the NVML shared library isn't installed and GPU-Viewer doesn't report an nvidia card in the machine.

**Comment by TingPing** [comment]
I no longer use an nvidia card so this might need somebody else to pick this up and finish it.

**Comment by foundObjects** [comment]
Some for anyone who decides to pick this up:

Some of the incompatibility I mentioned above isn't actually due to the package missing files, nvidia broke compatibility with a few things in 535. Apparently there are new files to package in the 535 driver as well:

https://github.com/Frogging-Family/nvidia-all/issues/169

https://forums.developer.nvidia.com/t/nvml-12-535-43-02-breaks-backwards-compatibility/254999

**Comment by TingPing** [comment]
Superseded by #234

**Pull request closed without merging**
