### PR TITLE
Move 418.43 to Long Lived Versions

### PR DESCRIPTION
**Pull request by 404NetworkError**
https://www.nvidia.com/object/unix.html shows that 418.43 is actually a Long Lived Version instead of short.

### CODE REVIEW

**Comment by TingPing** [comment]
Needs rebase.

**Comment by 404NetworkError** [comment]
@TingPing Rebase completed.

**Comment by TingPing** [comment]
Looks like a bad rebase. `git pull --rebase origin master` perhaps.

**Comment by 404NetworkError** [comment]
Sorry about that. I believe it's fixed now.

**Pull request merged**
