### PR TITLE
Add Beta 565.57.01

### PR DESCRIPTION
**Pull request by dekomote**
Added the Beta driver 565.57.01

### CODE REVIEW

**Review by guihkx — CHANGES_REQUESTED** [review]
Please add that version to `BETA_VERSIONS`, and not to `NEW_FEATURE_VERSIONS`

**Comment by guihkx** [comment]
Thanks! Out of curiosity, did you build and test this version [locally](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia?tab=readme-ov-file#building-locally)? I would, but I can't because my GPU is too old and this driver wouldn't work anyway.

Although, files-wise, there hasn't been any major changes between `560.35.03` (current stable) and `565.57.01` (this beta), so maybe testing it isn't necessary:

```bash
$ cd ~/NVIDIA-Linux-x86_64-560.35.03
$ tree -fv -I 'kernel/' -I 'kernel-open/' -I 'html/' | perl -pe 's/(?<=\.so)\.560\..+//g' > ~/560.35.03.txt
$ cd ~/NVIDIA-Linux-x86_64-565.57.01
$ tree -fv -I 'kernel/' -I 'kernel-open/' -I 'html/' | perl -pe 's/(?<=\.so)\.565\..+//g' > ~/565.57.01.txt
$ git diff --no-index ~/560.35.03.txt ~/565.57.01.txt
```

```diff
diff --git a/home/gui/560.35.03.txt b/home/gui/565.57.01.txt
index 152d9d3..8a7bebe 100644
--- a/home/gui/560.35.03.txt
+++ b/home/gui/565.57.01.txt
@@ -23,10 +23,10 @@
 │   │   └── ./32/libglvnd_install_checker/libGLX_installcheck.so.0
 │   ├── ./32/libnvcuvid.so
 │   ├── ./32/libnvidia-allocator.so
-│   ├── ./32/libnvidia-egl-gbm.so.1.1.1
-│   ├── ./32/libnvidia-egl-wayland.so.1.1.13
-│   ├── ./32/libnvidia-egl-xcb.so.1
-│   ├── ./32/libnvidia-egl-xlib.so.1
+│   ├── ./32/libnvidia-egl-gbm.so.1.1.2
+│   ├── ./32/libnvidia-egl-wayland.so.1.1.17
+│   ├── ./32/libnvidia-egl-xcb.so.1.0.0
+│   ├── ./32/libnvidia-egl-xlib.so.1.0.0
 │   ├── ./32/libnvidia-eglcore.so
 │   ├── ./32/libnvidia-encode.so
 │   ├── ./32/libnvidia-fbc.so
@@ -73,10 +73,10 @@
 ├── ./libnvidia-allocator.so
 ├── ./libnvidia-api.so.1
 ├── ./libnvidia-cfg.so
-├── ./libnvidia-egl-gbm.so.1.1.1
-├── ./libnvidia-egl-wayland.so.1.1.13
-├── ./libnvidia-egl-xcb.so.1
-├── ./libnvidia-egl-xlib.so.1
+├── ./libnvidia-egl-gbm.so.1.1.2
+├── ./libnvidia-egl-wayland.so.1.1.17
+├── ./libnvidia-egl-xcb.so.1.0.0
+├── ./libnvidia-egl-xlib.so.1.0.0
 ├── ./libnvidia-eglcore.so
 ├── ./libnvidia-encode.so
 ├── ./libnvidia-fbc.so
@@ -95,6 +95,7 @@
 ├── ./libnvidia-pkcs11.so
 ├── ./libnvidia-ptxjitcompiler.so
 ├── ./libnvidia-rtcore.so
+├── ./libnvidia-sandboxutils.so
 ├── ./libnvidia-tls.so
 ├── ./libnvidia-vksc-core.so
 ├── ./libnvidia-wayland-client.so
@@ -103,8 +104,8 @@
 ├── ./makeself-help-script.sh
 ├── ./makeself.sh
 ├── ./mkprecompiled
-├── ./nvidia-application-profiles-560.35.03-key-documentation
-├── ./nvidia-application-profiles-560.35.03-rc
+├── ./nvidia-application-profiles-565.57.01-key-documentation
+├── ./nvidia-application-profiles-565.57.01-rc
 ├── ./nvidia-bug-report.sh
 ├── ./nvidia-cuda-mps-control
 ├── ./nvidia-cuda-mps-control.1.gz
@@ -151,4 +152,4 @@
     └── ./systemd/system-sleep
         └── ./systemd/system-sleep/nvidia
 
-9 directories, 143 files
+9 directories, 144 files


```

**Comment by dekomote** [comment]
> Out of curiosity, did you build and test this version [locally](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia?tab=readme-ov-file#building-locally)?

I did. I am currently using it. I tested it with few games as well as prusa slicer (I needed it for this actually).

**Review by guihkx — APPROVED** [review]
Great, let's merge then.

**Pull request merged**
